# setup lb 
---
  - hosts: lb
    tasks:
      - name: Copy LB Config
        template:
          src: ../config/nginx.j2
          dest: /etc/nginx/nginx.conf
          owner: root
          group: root
          mode: 0644
        notify: Stop Start Nginx

    handlers:
      - name: Stop Start Nginx
        shell: nginx -s stop
        notify: Reload NGiNX

      - name: Reload NGiNX
        shell: nginx

